In [85]:
import numpy as np 
import pandas as pd
arr=np.array([[2,2,-2],[2,-1,4],[-2,4,-1]])

In [86]:
arr

array([[ 2,  2, -2],
       [ 2, -1,  4],
       [-2,  4, -1]])

In [87]:
eigenvalues=np.linalg.eigvals(arr)
eigenvalues

array([ 3., -6.,  3.])

In [88]:
ev,evector=np.linalg.eigh(arr)

In [89]:
ev

array([-6.,  3.,  3.])

In [90]:
evector

array([[-0.33333333,  0.07875591,  0.93951391],
       [ 0.66666667,  0.72432441,  0.17581154],
       [-0.66666667,  0.68494646, -0.29394541]])

In [91]:
evector

array([[-0.33333333,  0.07875591,  0.93951391],
       [ 0.66666667,  0.72432441,  0.17581154],
       [-0.66666667,  0.68494646, -0.29394541]])

In [92]:
evector=evector

In [93]:
p=evector

In [94]:
p_1=np.linalg.inv(p)

In [95]:
a=np.dot(p_1,arr)

In [96]:
answer=np.dot(a,p)

In [97]:
answer

array([[-6.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.88178420e-16,  3.00000000e+00,  0.00000000e+00],
       [-2.22044605e-15,  1.11022302e-16,  3.00000000e+00]])

In [98]:
np.round_(answer,2)

array([[-6.,  0.,  0.],
       [-0.,  3.,  0.],
       [-0.,  0.,  3.]])